# Generated by Django 3.2.5 on 2021-07-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_do', models.CharField(max_length=200)),
                ('first_name_taken', models.CharField(max_length=200)),
                ('last_name_taken', models.CharField(max_length=200)),
                ('phone_number_taken', models.CharField(max_length=200)),
                ('email_id_taken', models.EmailField(max_length=200)),
                ('description_taken', models.CharField(max_length=300)),
            ],
        ),
    ]
