# Generated by Django 3.2.5 on 2021-07-31 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmark_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_do',
            new_name='applied_for',
        ),
    ]
