# Generated by Django 3.2.5 on 2021-07-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmark_profile', '0002_rename_employee_do_employee_applied_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='description_taken',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
