# Generated by Django 3.2.5 on 2021-07-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmark_profile', '0003_alter_employee_description_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
